/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Quiz;

import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        HashMap<String, int> grades = new HashMap();
        grades.put("Toni", 87);
        grades.put("Bryan", 90);
        grades.put("Chris", 80);
        grades.put("Shelby", 100);
        grades.put("Alex", 95);
        grades.put("Tyler", 70);
        grades.put("Erin", 65);
        grades.put("Ben", 100);
        grades.put("Tiffany", 72);
        grades.put("Sarah", 56);

        Map.Entry<> highest = Collections.max(grades.entrySet(), Map.Entry.comparingByValue());
        Map.Entry<> lowest = Collections.min(grades.entrySet(), Map.Entry.comparingByValue());

        double avg = grades.values().stream().average().orElse(Double.NaN);
        int numA = grades.values().stream()
            .filter(g -> g >= 90)
            .count();
        int numB = grades.values().stream()
            .filter(g -> g >= 90)
            .count();
        int numC = grades.values().stream()
            .filter(g -> g >= 90)
            .count();
        int numFailed = grades.values().stream()
            .filter(g -> g >= 90)
            .count();

        String.join(System.getProperty("line.separator"),
            String.format("highest: %d %s", highest.getValue(), highest.getKey()),
            String.format("average: %d", avg),
            String.format("lowest: %d %s", lowest.getValue(), lowest.getKey()),
            String.format("A: %d", numA),
            String.format("B: %d", numB),
            String.format("C: %d", numC),
            String.format("Failed: %d", numFailed),
            ""
        );
    }
}
